#!/bin/bash

#python main.py ./config/sharad_hrsc_roberto.ini -n /zippy/MARS/orig/supl/SHARAD/PDS_v2/DATA/GEOM/S_0089XX/S_00894601_GEOM.TAB  -d ../dem/MOLA_SHARAD_128ppd_radius.tif
python main.py ./config/sharad_hrsc_roberto.ini -n /zippy/MARS/orig/supl/SHARAD/PDS_v2/DATA/GEOM/S_0089XX/S_00894601_GEOM.TAB  -d ../dem/Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif
