[paths]
outPath = /zippy/MARS/targ/modl/simc/SHARAD_CTX_SIM/ctDist45k_sharad_DM
demPath =
navPath = 
sigPath = 

[navigation]
navsys = +proj=longlat +R=470000 +no_defs
navfunc = GetNav_MatisseCeres

[simParams]
speedLight = 299792458
dt = 37.5e-9
traceSamples = 3600
body = ceres
demBump = True
demInterp = False
#when centerPlane is set to True, sim.py calculates the center coordinates of the plane 
centerPlane = True
antenna_pattern = none
swathAngle = 5

[facetParams]
atDist = 300
ctDist = 30000
atStep = 30
ctStep = 10

[outputs]
showNadir =True
showFret = True
combinedAdj = True
combined = True
combinedColored = True
left = True
right = True
binary = True
echomap = True
echomapAdj = True
echomapColored = True
echomapGeoref = False
red = True
nadir = True
fret = true
#Export facets require center_plane = True
exportFacetsArray = False
exportFacetsArrayH5 = False
